"""Fix UUID field length

Revision ID: 151443197397
Revises: 
Create Date: 2024-12-02 03:02:50.041637

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '151443197397'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otprecord', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=200),
               nullable=True)
    op.create_index(op.f('ix_otprecord_email'), 'otprecord', ['email'], unique=True)
    op.alter_column('user', 'uuid',
               existing_type=mysql.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=200),
               existing_nullable=False)
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    op.alter_column('userprofile', 'user_uuid',
               existing_type=mysql.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userprofile', 'user_uuid',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.alter_column('user', 'uuid',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_otprecord_email'), table_name='otprecord')
    op.alter_column('otprecord', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=200),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
