"""added added new modefffls

Revision ID: 75e79d5e6ce3
Revises: 1bdfaa22805f
Create Date: 2024-12-18 05:47:36.692732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '75e79d5e6ce3'
down_revision: Union[str, None] = '1bdfaa22805f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id_2', table_name='otprecords', mysql_length={'user_id': 250})
    op.create_foreign_key(None, 'otprecords', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['id'])
    op.drop_index('created_by_2', table_name='todolist', mysql_length={'created_by': 250})
    op.create_foreign_key(None, 'todolist', 'user', ['created_by'], ['id'])
    op.add_column('userfollower', sa.Column('follower_profile_id', sa.Integer(), nullable=True))
    op.add_column('userfollower', sa.Column('followed_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userfollower', 'profile', ['followed_profile_id'], ['id'])
    op.create_foreign_key(None, 'userfollower', 'profile', ['follower_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userfollower', type_='foreignkey')
    op.drop_constraint(None, 'userfollower', type_='foreignkey')
    op.drop_column('userfollower', 'followed_profile_id')
    op.drop_column('userfollower', 'follower_profile_id')
    op.drop_constraint(None, 'todolist', type_='foreignkey')
    op.create_index('created_by_2', 'todolist', ['created_by'], unique=False, mysql_length={'created_by': 250})
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_constraint(None, 'otprecords', type_='foreignkey')
    op.create_index('user_id_2', 'otprecords', ['user_id'], unique=False, mysql_length={'user_id': 250})
    # ### end Alembic commands ###
