"""added firtname

Revision ID: 84798ddd307f
Revises: f14baacf13af
Create Date: 2024-12-15 18:08:52.372231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '84798ddd307f'
down_revision: Union[str, None] = 'f14baacf13af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id_2', table_name='otprecords', mysql_length={'user_id': 250})
    op.create_foreign_key(None, 'otprecords', 'user', ['user_id'], ['id'])
    op.drop_index('created_by_2', table_name='todolist', mysql_length={'created_by': 250})
    op.create_foreign_key(None, 'todolist', 'user', ['created_by'], ['id'])
    op.add_column('user', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.drop_index('ix_user_fist_name', table_name='user')
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.drop_column('user', 'fist_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fist_name', mysql.VARCHAR(length=200), nullable=False))
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.create_index('ix_user_fist_name', 'user', ['fist_name'], unique=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.drop_column('user', 'first_name')
    op.drop_constraint(None, 'todolist', type_='foreignkey')
    op.create_index('created_by_2', 'todolist', ['created_by'], unique=False, mysql_length={'created_by': 250})
    op.drop_constraint(None, 'otprecords', type_='foreignkey')
    op.create_index('user_id_2', 'otprecords', ['user_id'], unique=False, mysql_length={'user_id': 250})
    # ### end Alembic commands ###
