"""update the id project

Revision ID: b22dbc3ccfc2
Revises: e723d9b831b2
Create Date: 2024-12-20 05:58:19.928074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b22dbc3ccfc2'
down_revision: Union[str, None] = 'e723d9b831b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id_2', table_name='otprecords', mysql_length={'user_id': 250})
    op.create_foreign_key(None, 'otprecords', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['id'])
    op.drop_index('created_by_2', table_name='todolist', mysql_length={'created_by': 250})
    op.create_foreign_key(None, 'todolist', 'user', ['created_by'], ['id'])
    op.add_column('userfollower', sa.Column('follower_id', sa.Integer(), nullable=False))
    op.add_column('userfollower', sa.Column('followed_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'userfollower', 'profile', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'userfollower', 'profile', ['followed_id'], ['id'])
    op.drop_column('userfollower', 'followed_profile_id')
    op.drop_column('userfollower', 'follower_profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userfollower', sa.Column('follower_profile_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('userfollower', sa.Column('followed_profile_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'userfollower', type_='foreignkey')
    op.drop_constraint(None, 'userfollower', type_='foreignkey')
    op.drop_column('userfollower', 'followed_id')
    op.drop_column('userfollower', 'follower_id')
    op.drop_constraint(None, 'todolist', type_='foreignkey')
    op.create_index('created_by_2', 'todolist', ['created_by'], unique=False, mysql_length={'created_by': 250})
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_constraint(None, 'otprecords', type_='foreignkey')
    op.create_index('user_id_2', 'otprecords', ['user_id'], unique=False, mysql_length={'user_id': 250})
    # ### end Alembic commands ###
