"""image update

Revision ID: bad04bc49b5d
Revises: 4114af262963
Create Date: 2024-12-31 14:31:16.063342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bad04bc49b5d'
down_revision: Union[str, None] = '4114af262963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'commentreaction', 'comment', ['comment_id'], ['id'])
    op.create_foreign_key(None, 'commentreaction', 'user', ['user_id'], ['id'])
    op.drop_index('user_id_2', table_name='otprecords', mysql_length={'user_id': 250})
    op.create_foreign_key(None, 'otprecords', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'postimage', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'postlike', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'postlike', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'posttag', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'posttag', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['id'])
    op.drop_index('created_by_2', table_name='todolist', mysql_length={'created_by': 250})
    op.create_foreign_key(None, 'todolist', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'userfollower', 'profile', ['followed_id'], ['id'])
    op.create_foreign_key(None, 'userfollower', 'profile', ['follower_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userfollower', type_='foreignkey')
    op.drop_constraint(None, 'userfollower', type_='foreignkey')
    op.drop_constraint(None, 'todolist', type_='foreignkey')
    op.create_index('created_by_2', 'todolist', ['created_by'], unique=False, mysql_length={'created_by': 250})
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_constraint(None, 'posttag', type_='foreignkey')
    op.drop_constraint(None, 'posttag', type_='foreignkey')
    op.drop_constraint(None, 'postlike', type_='foreignkey')
    op.drop_constraint(None, 'postlike', type_='foreignkey')
    op.drop_constraint(None, 'postimage', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'otprecords', type_='foreignkey')
    op.create_index('user_id_2', 'otprecords', ['user_id'], unique=False, mysql_length={'user_id': 250})
    op.drop_constraint(None, 'commentreaction', type_='foreignkey')
    op.drop_constraint(None, 'commentreaction', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
