"""Update user add lastname

Revision ID: c7dfff4d16c9
Revises: 0251b033463e
Create Date: 2024-12-06 02:36:22.068517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7dfff4d16c9'
down_revision: Union[str, None] = '0251b033463e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'otprecords', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False))
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_column('user', 'last_name')
    op.drop_constraint(None, 'otprecords', type_='foreignkey')
    # ### end Alembic commands ###
